# Use the official Docker Hub Postgres image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=trades

# Set the working directory in the container to /docker-entrypoint-initdb.d
WORKDIR /docker-entrypoint-initdb.d

# Copy the SQL scripts into the Docker image
COPY ./init.sql ./

# Copy trades.csv into the Docker image
COPY ./trades.csv ./

# Run the SQL scripts on startup
RUN echo "COPY TRADES FROM '/docker-entrypoint-initdb.d/trades.csv' DELIMITER ',' CSV HEADER;" >> /docker-entrypoint-initdb.d/init.sql
