# Use the official Docker Hub Postgres image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=tradedb

# Set the working directory in the container to /docker-entrypoint-initdb.d
WORKDIR /docker-entrypoint-initdb.d

# Copy the SQL scripts into the Docker image
COPY ./init.sql ./

# Copy trades.csv into the Docker image
COPY ./trades.csv ./
