# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Install dbt-core and dbt-postgres
RUN pip install dbt-core dbt-postgres

# Keep the container running
CMD ["tail", "-f", "/dev/null"]